### ISSUE TITLE
[Tailor] Spesial request will visible if order has it?

### ISSUE THREAD

**Issue by blasiusneri** [syntialai/TailorMade-mobile#61]
![Screenshot_20210204-084801](https://user-images.githubusercontent.com/6764955/106833339-ef0b0780-66c5-11eb-8f8a-822e4a7b2517.png)

**Comment by syntialai** [comment]
Yes, it will be shown in order detail page kak. Fixed in backend and now the instructions must be shown when checkout new cart item kak
